### ISSUE TITLE
Error on build - GLFWObject

### ISSUE THREAD

**Issue by Its-Kenta** [ThePotatoKing55/SwiftGLFW#2]
Hello,

I'm getting an error on build with the following output:

`
error: protocol 'GLFWObject' can only be used as a generic constraint because it has Self or associated type requirements
    public static func == (lhs: Self, rhs: any GLFWObject) -> Bool {
`

**Comment by ThePotatoKing55** [comment]
Should be fixed with #3 — replaced with generic.
